# Session 2 Assignment B
### Step 0: Read Input and Output

In [43]:
import numpy as np
x = [[1,0,1,0],[1,0,1,1],[0,1,0,1]]
y = ([1],[1],[0])

# Converting list to numpy array

x = np.array(x)
y = np.array(y)

### Step 1: Initialize weights and biases with random values 
(There are methods to initialize weights and biases but for now initialize with random values)

In [44]:
#wh = [[.78,.65,.23],[.87,.56,.32],[.19,.48,.92],[.66,.71,.29]]
#bh = [[.36,.72,.02]]
#wout = [[.39],[.47],[.23]]
#bout=[.54]

# Converting list to numpy array

#wh = np.array(wh)
#bh = np.array(bh)
#wout = np.array(wout)
#bout = np.array(bout)

#Using random function to generate values
wh = np.random.random_sample([4,3])
bh = np.random.random_sample([1,3])
wout = np.random.random_sample([3,1])
bout = np.random.random_sample([1,1])


print("\n",wh)
print("\n", bh)

print("\n", wout)
print("\n", bout)



 [[ 0.89697962  0.19567117  0.13627549]
 [ 0.64979427  0.2119181   0.87490872]
 [ 0.41861207  0.69023298  0.50828092]
 [ 0.03300463  0.17206479  0.33577203]]

 [[ 0.60773136  0.06845338  0.63357769]]

 [[ 0.40871202]
 [ 0.23459474]
 [ 0.427355  ]]

 [[ 0.21965703]]


### Step 2: Calculate hidden layer input:

 hidden_layer_input = matrix_dot_product(X,wh) + bh

In [45]:
hidden_layer = np.dot(x,wh) + bh

### Step 3: Perform non-linear transformation on hidden linear input
 hiddenlayer_activations = sigmoid(hidden_layer_input)

In [46]:
# Sigmoid Function
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

hidden_act = []

In [47]:
for i in range(0,3):
    arr=[]
    for j in range(0,3):
        arr.append(sigmoid(hidden_layer[i][j]))
    hidden_act.append(arr)
hidden_act = np.array(hidden_act)

### Step 4: Perform linear and non-linear transformation of hidden layer activation at output layer

output_layer_input = matrix_dot_product (hiddenlayer_activations * wout ) + bout output = sigmoid(output_layer_input)

In [48]:
output_layer = np.dot(hidden_act,wout) +bout

In [49]:
output = np.empty([3,1])
for i in range(0,3):
    output[i,0]= sigmoid(output_layer[i,0])

### Step 5: Calculate gradient of Error(E) at output layer
 E = y-output

In [50]:
Error = np.subtract(y,output)

### Step 6: Compute slope at output and hidden layer

 Slope_output_layer= derivatives_sigmoid(output)

Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)`

In [51]:
# derivative of Sigmoid function
def d_sig(x):
    return(x*(1-x))

slope_output=np.empty([3,1])

In [52]:
for i in range(0,3):
    slope_output[i,0] = d_sig(output[i,0])
slope_output

slope_hidden=np.empty([3,3])
for i in range(0,3):
    for j in range(0,3):
        slope_hidden[i,j] = d_sig(hidden_act[i,j])
slope_hidden 

array([[ 0.11123739,  0.20072014,  0.17040154],
       [ 0.10852248,  0.18488417,  0.1384754 ],
       [ 0.16920937,  0.23763049,  0.11790296]])

### Step 7: Compute delta at output layer

d_output = E * slope_output_layer

In [53]:
d_output = slope_output*Error
d_output

array([[ 0.0479805 ],
       [ 0.04613544],
       [-0.14216749]])

In [54]:
wout.shape

(3, 1)

### Step 8: Calculate Error at hidden layer

 Error_at_hidden_layer = matrix_dot_product(d_output, wout.Transpose)



In [55]:
hidden_error = np.dot(d_output,np.transpose(wout))

### Step 9: Compute delta at hidden layer

 d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

In [56]:
d_hidden = hidden_error*slope_hidden

In [57]:
d_hidden

array([[ 0.00218139,  0.0022593 ,  0.00349403],
       [ 0.00204631,  0.00200103,  0.00273021],
       [-0.00983201, -0.00792539, -0.00716331]])

### Step 10: Update weight at both output and hidden layer

 wout = wout + matrix_dot_product (hiddenlayer_activations.Transpose, d_output) * learning_rate

 wh = wh+ matrix_dot_product (X.Transpose,d_hiddenlayer) * learning_rate

 learning_rate is 0.1

In [58]:
learning_rate = 0.1
wout = np.add(wout,np.dot(np.transpose(hidden_act),d_output)*learning_rate)
wh = np.add(wh,np.dot(np.transpose(x),d_hidden)*learning_rate)

### Step 11: Update biases at both output and hidden layer

 bh = bh + sum(d_hiddenlayer, axis=0) * learning_rate
 
 bout = bout + sum(d_output, axis=0)*learning_rate

In [59]:
bh = bh + np.sum(d_hidden)*learning_rate
bout = bout + np.sum(d_output)*learning_rate

### Output

In [60]:
print(x)
print("\n",wh)
print("\n", bh)
print("\n", hidden_layer)
print("\n", hidden_act)
print("\n", wout)
print("\n", bout)
print("\n", output)
print("\n", y)
print("\n", Error)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]

 [[ 0.89740239  0.1960972   0.13689791]
 [ 0.64881107  0.21112556  0.87419239]
 [ 0.41903484  0.69065901  0.50890334]
 [ 0.03222606  0.17147235  0.33532872]]

 [[ 0.60671051  0.06743253  0.63255685]]

 [[ 1.92332305  0.95435752  1.2781341 ]
 [ 1.95632768  1.12642231  1.61390613]
 [ 1.29053025  0.45243626  1.84425844]]

 [[ 0.87250854  0.72199067  0.78213199]
 [ 0.87613497  0.75517805  0.83395299]
 [ 0.78423693  0.61121832  0.86345157]]

 [[ 0.40579114]
 [ 0.23285339]
 [ 0.42267971]]

 [[ 0.21485187]]

 [[ 0.74647222]
 [ 0.75237115]
 [ 0.74126868]]

 [[1]
 [1]
 [0]]

 [[ 0.25352778]
 [ 0.24762885]
 [-0.74126868]]


In [61]:
print(slope_hidden)
print("\n", hidden_error)
print("\n", slope_output)
print("\n", d_hidden)
print("\n", d_output)



[[ 0.11123739  0.20072014  0.17040154]
 [ 0.10852248  0.18488417  0.1384754 ]
 [ 0.16920937  0.23763049  0.11790296]]

 [[ 0.01961021  0.01125597  0.02050471]
 [ 0.01885611  0.01082313  0.01971621]
 [-0.05810556 -0.03335175 -0.06075599]]

 [[ 0.18925145]
 [ 0.1863088 ]
 [ 0.19178942]]

 [[ 0.00218139  0.0022593   0.00349403]
 [ 0.00204631  0.00200103  0.00273021]
 [-0.00983201 -0.00792539 -0.00716331]]

 [[ 0.0479805 ]
 [ 0.04613544]
 [-0.14216749]]
